---
#
# Installs Mailcatcher and makes it start automatically on every system boot
#
# May be helpful: https://github.com/heybigname/ansible

# Install a more recent version of ruby
# @see http://venturecraft.com.au/development/installing-mailcatcher-with-homestead-vagrant/
- name: install ruby 1.9.1 and other dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - ruby1.9.1-dev
    - libsqlite3-dev
    - make
    - g++
  sudo: true

- name: install mailcatcher
  command: gem install mailcatcher creates=/usr/local/bin/mailcatcher
  sudo: true

- name: setup mailcatcher service
  copy: src=upstart/mailcatcher.conf dest=/etc/init/mailcatcher.conf

- name: Start mailcatcher service
  service: name=mailcatcher state=started

#- name: MailCatcher | Configure PHP.ini
#  command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php5/fpm/php.ini
#  command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php5/cli/php.ini
#  when: install_web == "yes"