---
- name: install php5 modules
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - php-pear
    - php5-curl
    - php5-mcrypt
    - php5-intl
    - php5-gmp
    - php5-imap
    - php5-mysqlnd # "mysqlnd" is PHP's native MySQL driver and is therefore to be prefered to "mysql"
    - php5-pgsql
    - php5-sqlite
    - php5-gd
    - php5-imagick
    - php5-json