---
#
# Installs PHP5 with most used modules, Xdebug and PHP FPM
#

- include: prereq.yml

- name: add apt php 5.6 repository
  apt_repository: repo='ppa:ondrej/php5-5.6' update_cache=yes

- name: install php5
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - php5
    - php5-dev
    - php5-cli

- include: install-modules.yml

- include: install-xdebug.yml

- include: php-fpm.yml