---
#
# Installs PHP5 with most used modules, Xdebug and PHP FPM
#

- include: prereq.yml

- name: add apt php5 repository
  # The php5-oldstable repo contains PHP 5.4 as of writing this code (08/2015)
  apt_repository: repo='ppa:ondrej/php5-oldstable' update_cache=yes

- name: install php5
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - php5
    - php5-dev
    - php5-cli

- include: install-modules.yml

- include: install-xdebug.yml

- include: php-fpm.yml