---
- name: install PHP FPM
  apt: pkg=php5-fpm update_cache=yes cache_valid_time=3600

#- name: copy php.ini for PHP FPM
#  copy:
#    src: php-fpm/php.ini
#    dest: /etc/php5/fpm/php.ini
#    mode: 0644
#  notify: restart php-fpm

- name: set the PHP FPM listen address
  ini_file:
    dest: /etc/php5/fpm/pool.d/www.conf
    section: www
    option: listen
    value: 127.0.0.1:9000
  notify: restart php-fpm
