---
- name: Set up the Vagrant development server
  hosts: localhost
  roles:
    - role: apache2
      public_folder: public
#    - role: nginx
#      public_folder: public
    - role: php5
    - role: mysql
    - role: martinmicunda.nodejs
    - role: martinmicunda.bower
    - role: geerlingguy.mailhog